import type { Objective } from '@/hooks/useObjectives'
import type { CheckInSummary } from '@/lib/checkin-summary'
import type { Comment } from '@/hooks/useComments'
import type { AppNotification } from '@/hooks/useNotifications'

export const demoUsers = [
  { id: 'user-admin', name: 'Avery CEO', email: 'avery@okrflow.demo', role: 'ADMIN' },
  { id: 'user-manager', name: 'Morgan Lead', email: 'morgan@okrflow.demo', role: 'MANAGER' },
  { id: 'user-employee', name: 'Eden IC', email: 'eden@okrflow.demo', role: 'EMPLOYEE' },
  { id: 'user-emea', name: 'Lea Ops', email: 'lea@okrflow.demo', role: 'MANAGER' },
  { id: 'user-apac', name: 'Kenji PM', email: 'kenji@okrflow.demo', role: 'MANAGER' },
  { id: 'user-data', name: 'Ravi Data', email: 'ravi@okrflow.demo', role: 'EMPLOYEE' },
  { id: 'user-eng', name: 'Priya Eng', email: 'priya@okrflow.demo', role: 'EMPLOYEE' },
  { id: 'user-sales', name: 'Diego AE', email: 'diego@okrflow.demo', role: 'EMPLOYEE' },
  { id: 'user-latam', name: 'Sofia CS', email: 'sofia@okrflow.demo', role: 'EMPLOYEE' },
] as const

export const demoTeams = [
  {
    id: 'team-gtm',
    name: 'Growth',
    members: [demoUsers[1], demoUsers[2], demoUsers[7]],
  },
  {
    id: 'team-product',
    name: 'Product',
    members: [demoUsers[0], demoUsers[2], demoUsers[6]],
  },
  {
    id: 'team-cs',
    name: 'Customer Success',
    members: [demoUsers[1]],
  },
  {
    id: 'team-sales',
    name: 'Sales',
    members: [demoUsers[0], demoUsers[1], demoUsers[7]],
  },
  {
    id: 'team-emea',
    name: 'EMEA Expansion',
    members: [demoUsers[3], demoUsers[8]],
  },
  {
    id: 'team-apac',
    name: 'APAC Growth',
    members: [demoUsers[4], demoUsers[6]],
  },
  {
    id: 'team-platform',
    name: 'Platform & Data',
    members: [demoUsers[5], demoUsers[6]],
  },
  {
    id: 'team-support',
    name: 'Support & LATAM',
    members: [demoUsers[8]],
  },
]

const today = new Date()
const start = new Date(today.getFullYear(), 9, 1).toISOString()
const end = new Date(today.getFullYear(), 11, 31).toISOString()

export const demoObjectives: Objective[] = [
  {
    id: 'obj-company-1',
    title: 'Expand into 2 new markets',
    description: 'Land lighthouse customers in APAC and EU',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'COMPANY',
    progressType: 'AUTOMATIC',
    progress: 63,
    score: 0.7,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: null,
    parent: null,
    children: [
      { id: 'obj-team-1', title: 'Increase qualified pipeline 40%' },
      { id: 'obj-team-2', title: 'Improve product onboarding' },
    ],
    keyResults: [
      { id: 'kr-company-1', title: 'Signed ARR from new regions', weight: 40, target: 1000000, current: 620000, unit: 'USD', progress: 62, initiativeCount: 3 },
      { id: 'kr-company-2', title: 'Regional NPS > 70', weight: 30, target: 70, current: 52, progress: 74, initiativeCount: 2 },
      { id: 'kr-company-3', title: 'Partner pipeline sources 30%', weight: 30, target: 30, current: 18, progress: 60, initiativeCount: 1 },
    ],
    _count: { children: 2 },
  },
  {
    id: 'obj-team-1',
    title: 'Increase qualified pipeline 40%',
    description: 'Focus on PLG and outbound efficiency',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 72,
    score: 0.78,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[1],
    team: demoTeams[0],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [{ id: 'obj-ic-1', title: 'Launch ABM motion' }],
    keyResults: [
      { id: 'kr-team-1', title: 'Outbound reply rate 12%+', weight: 30, target: 12, current: 10.5, unit: '%', progress: 88, initiativeCount: 4 },
      { id: 'kr-team-2', title: 'SQL to Opp conversion 35%', weight: 30, target: 35, current: 28, unit: '%', progress: 80, initiativeCount: 2 },
      { id: 'kr-team-3', title: 'Pipeline coverage 4.5x', weight: 40, target: 4.5, current: 3.2, progress: 71, initiativeCount: 3 },
    ],
    _count: { children: 1 },
  },
  {
    id: 'obj-team-2',
    title: 'Improve product onboarding',
    description: 'Reduce time-to-value and activation drop-offs',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 58,
    score: 0.64,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: demoTeams[1],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [{ id: 'obj-ic-2', title: 'Optimize onboarding funnel' }],
    keyResults: [
      { id: 'kr-team-4', title: 'Activation rate 65%', weight: 40, target: 65, current: 52, unit: '%', progress: 80, initiativeCount: 2 },
      { id: 'kr-team-5', title: 'Time to first value < 1 day', weight: 30, target: 1, current: 1.4, unit: 'days', progress: 60, initiativeCount: 2 },
      { id: 'kr-team-6', title: 'Onboarding drop-off < 25%', weight: 30, target: 25, current: 33, unit: '%', progress: 64, initiativeCount: 1 },
    ],
    _count: { children: 1 },
  },
  {
    id: 'obj-team-3',
    title: 'Reduce churn to <4%',
    description: 'Improve adoption and renewals in top 50 accounts',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 66,
    score: 0.74,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[1],
    team: demoTeams[2],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-team-7', title: 'NPS > 55', weight: 40, target: 55, current: 49, unit: 'score', progress: 89, initiativeCount: 2 },
      { id: 'kr-team-8', title: 'Gross churn <4%', weight: 30, target: 4, current: 5.4, unit: '%', progress: 73, initiativeCount: 2 },
      { id: 'kr-team-9', title: 'Adoption in top 50 accounts 70%', weight: 30, target: 70, current: 54, unit: '%', progress: 77, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-team-4',
    title: 'Accelerate enterprise deals',
    description: 'Land 3 enterprise wins and expand ACV',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 54,
    score: 0.6,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: demoTeams[3],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-team-10', title: 'Enterprise ACV $1.5M', weight: 40, target: 1500000, current: 820000, unit: 'USD', progress: 55, initiativeCount: 3 },
      { id: 'kr-team-11', title: 'Win rate 28%', weight: 30, target: 28, current: 21, unit: '%', progress: 75, initiativeCount: 2 },
      { id: 'kr-team-12', title: 'Discovery-to-demo < 5 days', weight: 30, target: 5, current: 7, unit: 'days', progress: 60, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-ic-1',
    title: 'Launch ABM motion',
    description: 'Pilot ABM for top 50 accounts',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'INDIVIDUAL',
    progressType: 'AUTOMATIC',
    progress: 76,
    score: 0.82,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[2],
    team: demoTeams[0],
    parent: { id: 'obj-team-1', title: 'Increase qualified pipeline 40%' },
    children: [],
    keyResults: [
      { id: 'kr-ic-1', title: 'Target list coverage 95%', weight: 40, target: 95, current: 92, unit: '%', progress: 97, initiativeCount: 2 },
      { id: 'kr-ic-2', title: 'Warm intro meetings 30', weight: 30, target: 30, current: 18, progress: 60, initiativeCount: 2 },
      { id: 'kr-ic-3', title: 'ABM influenced pipeline $250k', weight: 30, target: 250000, current: 140000, progress: 56, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-ic-2',
    title: 'Optimize onboarding funnel',
    description: 'Increase guided onboarding completion',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'INDIVIDUAL',
    progressType: 'AUTOMATIC',
    progress: 48,
    score: 0.52,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[2],
    team: demoTeams[1],
    parent: { id: 'obj-team-2', title: 'Improve product onboarding' },
    children: [],
    keyResults: [
      { id: 'kr-ic-4', title: 'Guided onboarding completion 75%', weight: 50, target: 75, current: 48, unit: '%', progress: 64, initiativeCount: 2 },
      { id: 'kr-ic-5', title: 'Time to aha moment 15 min', weight: 25, target: 15, current: 22, unit: 'minutes', progress: 68, initiativeCount: 1 },
      { id: 'kr-ic-6', title: 'Onboarding CSAT 4.5', weight: 25, target: 4.5, current: 4.0, progress: 89, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-emea-1',
    title: 'Stabilize EMEA onboarding',
    description: 'Reduce churn and activation drop-offs across EU/MEA',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 49,
    score: 0.55,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[3],
    team: demoTeams[4],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-emea-1', title: 'EU activation rate 70%', weight: 40, target: 70, current: 46, unit: '%', progress: 66, initiativeCount: 3 },
      { id: 'kr-emea-2', title: 'Support response < 1h', weight: 30, target: 1, current: 1.6, unit: 'hours', progress: 42, initiativeCount: 2 },
      { id: 'kr-emea-3', title: 'Churn <5% in MEA', weight: 30, target: 5, current: 7.2, unit: '%', progress: 39, initiativeCount: 2 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-apac-1',
    title: 'Win APAC lighthouse accounts',
    description: 'Enterprise wins in Singapore, Sydney, and Tokyo',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 61,
    score: 0.68,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[4],
    team: demoTeams[5],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-apac-1', title: 'Signed ACV $750k', weight: 40, target: 750000, current: 420000, unit: 'USD', progress: 56, initiativeCount: 4 },
      { id: 'kr-apac-2', title: 'APAC NPS > 65', weight: 30, target: 65, current: 58, progress: 78, initiativeCount: 2 },
      { id: 'kr-apac-3', title: 'Local partner enablement 3', weight: 30, target: 3, current: 2, progress: 67, initiativeCount: 2 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-platform-1',
    title: 'Platform reliability & AI signals',
    description: 'Ship data platform to serve 100+ workspaces',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 57,
    score: 0.61,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[5],
    team: demoTeams[6],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [{ id: 'obj-ic-3', title: 'Harden data pipelines' }],
    keyResults: [
      { id: 'kr-platform-1', title: '99.9% uptime rolling 30d', weight: 40, target: 99.9, current: 99.4, unit: '%', progress: 74, initiativeCount: 3 },
      { id: 'kr-platform-2', title: 'Latency P95 < 300ms', weight: 30, target: 300, current: 420, unit: 'ms', progress: 48, initiativeCount: 2 },
      { id: 'kr-platform-3', title: 'AI check-in summaries GA', weight: 30, target: 1, current: 0.6, progress: 60, initiativeCount: 2 },
    ],
    _count: { children: 1 },
  },
  {
    id: 'obj-support-1',
    title: 'Bring LATAM support to green',
    description: 'Reduce backlog and response times for Spanish/Portuguese queues',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 44,
    score: 0.5,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[8],
    team: demoTeams[7],
    parent: { id: 'obj-team-3', title: 'Reduce churn to <4%' },
    children: [],
    keyResults: [
      { id: 'kr-support-1', title: 'Ticket backlog < 80', weight: 30, target: 80, current: 126, progress: 35, initiativeCount: 2 },
      { id: 'kr-support-2', title: 'CSAT > 4.6', weight: 35, target: 4.6, current: 4.2, progress: 70, initiativeCount: 2 },
      { id: 'kr-support-3', title: 'First reply < 15m', weight: 35, target: 15, current: 22, unit: 'minutes', progress: 41, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-sales-2',
    title: 'Enterprise renewals + upsell',
    description: 'Retain top 50 and expand seats where value is proven',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 52,
    score: 0.6,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[7],
    team: demoTeams[3],
    parent: { id: 'obj-team-4', title: 'Accelerate enterprise deals' },
    children: [],
    keyResults: [
      { id: 'kr-sales-1', title: 'Renewal rate 94%', weight: 40, target: 94, current: 90, unit: '%', progress: 82, initiativeCount: 2 },
      { id: 'kr-sales-2', title: 'Upsell ACV $400k', weight: 30, target: 400000, current: 180000, unit: 'USD', progress: 45, initiativeCount: 3 },
      { id: 'kr-sales-3', title: 'Time-to-close < 25d', weight: 30, target: 25, current: 32, unit: 'days', progress: 38, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-ic-3',
    title: 'Harden data pipelines',
    description: 'Resolve nightly failures and scale event ingestion',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'INDIVIDUAL',
    progressType: 'AUTOMATIC',
    progress: 38,
    score: 0.45,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[5],
    team: demoTeams[6],
    parent: { id: 'obj-platform-1', title: 'Platform reliability & AI signals' },
    children: [],
    keyResults: [
      { id: 'kr-ic-7', title: 'Ingestion error rate <0.1%', weight: 40, target: 0.1, current: 0.35, unit: '%', progress: 32, initiativeCount: 2 },
      { id: 'kr-ic-8', title: 'Backfill SLA < 2h', weight: 30, target: 2, current: 3.4, unit: 'hours', progress: 41, initiativeCount: 1 },
      { id: 'kr-ic-9', title: 'Data quality alerts automated', weight: 30, target: 1, current: 0.5, progress: 50, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
]

export const demoCheckInSummary: CheckInSummary = {
  hero: {
    avgProgress: 66,
    completionRate: 48,
    atRiskObjectives: 18,
    objectiveCount: 132,
    scoreAverage: 0.72,
  },
  weeklySummary: {
    onTrack: 68,
    atRisk: 22,
    offTrack: 9,
    dueThisWeek: 26,
  },
  teamHeatmap: [
    { teamId: 'team-gtm', teamName: 'Growth', progress: 72, status: 'green', objectiveCount: 18, memberCount: 26 },
    { teamId: 'team-product', teamName: 'Product', progress: 63, status: 'yellow', objectiveCount: 16, memberCount: 24 },
    { teamId: 'team-platform', teamName: 'Platform & Data', progress: 57, status: 'yellow', objectiveCount: 14, memberCount: 18 },
    { teamId: 'team-apac', teamName: 'APAC Growth', progress: 61, status: 'green', objectiveCount: 12, memberCount: 17 },
    { teamId: 'team-emea', teamName: 'EMEA Expansion', progress: 49, status: 'yellow', objectiveCount: 9, memberCount: 14 },
    { teamId: 'team-support', teamName: 'Support & LATAM', progress: 44, status: 'red', objectiveCount: 7, memberCount: 10 },
    { teamId: 'team-sales', teamName: 'Sales', progress: 54, status: 'yellow', objectiveCount: 15, memberCount: 22 },
  ],
  heatmap: [
    {
      keyResultId: 'kr-team-1',
      keyResultTitle: 'Outbound reply rate 12%+',
      objectiveTitle: 'Increase qualified pipeline 40%',
      ownerName: 'Morgan Lead',
      weeklyProgress: [
        { value: 72, status: 'green', date: new Date() },
        { value: 68, status: 'yellow', date: new Date() },
      ],
    },
    {
      keyResultId: 'kr-platform-2',
      keyResultTitle: 'Latency P95 < 300ms',
      objectiveTitle: 'Platform reliability & AI signals',
      ownerName: 'Ravi Data',
      weeklyProgress: [
        { value: 48, status: 'yellow', date: new Date() },
        { value: 35, status: 'red', date: new Date() },
      ],
    },
    {
      keyResultId: 'kr-team-5',
      keyResultTitle: 'Time to first value < 1 day',
      objectiveTitle: 'Improve product onboarding',
      ownerName: 'Avery CEO',
      weeklyProgress: [
        { value: 52, status: 'yellow', date: new Date() },
        { value: 60, status: 'green', date: new Date() },
      ],
    },
    {
      keyResultId: 'kr-support-1',
      keyResultTitle: 'Ticket backlog < 80',
      objectiveTitle: 'Bring LATAM support to green',
      ownerName: 'Sofia CS',
      weeklyProgress: [
        { value: 42, status: 'yellow', date: new Date() },
        { value: 28, status: 'red', date: new Date() },
      ],
    },
    {
      keyResultId: 'kr-apac-1',
      keyResultTitle: 'Signed ACV $750k',
      objectiveTitle: 'Win APAC lighthouse accounts',
      ownerName: 'Kenji PM',
      weeklyProgress: [
        { value: 56, status: 'yellow', date: new Date() },
        { value: 63, status: 'green', date: new Date() },
      ],
    },
  ],
  alignment: [
    {
      id: 'obj-company-1',
      title: 'Expand into 2 new markets',
      progress: 63,
      owner: 'Avery CEO',
      goalType: 'COMPANY',
      children: [
        {
          id: 'obj-team-1',
          title: 'Increase qualified pipeline 40%',
          progress: 72,
          owner: 'Morgan Lead',
          goalType: 'TEAM',
          children: [
            {
              id: 'obj-ic-1',
              title: 'Launch ABM motion',
              progress: 76,
              owner: 'Eden IC',
              goalType: 'INDIVIDUAL',
            },
          ],
        },
        {
          id: 'obj-team-2',
          title: 'Improve product onboarding',
          progress: 58,
          owner: 'Avery CEO',
          goalType: 'TEAM',
          children: [
            {
              id: 'obj-ic-2',
              title: 'Optimize onboarding funnel',
              progress: 48,
              owner: 'Eden IC',
              goalType: 'INDIVIDUAL',
            },
          ],
        },
        {
          id: 'obj-platform-1',
          title: 'Platform reliability & AI signals',
          progress: 57,
          owner: 'Ravi Data',
          goalType: 'TEAM',
        },
        {
          id: 'obj-team-3',
          title: 'Reduce churn to <4%',
          progress: 66,
          owner: 'Morgan Lead',
          goalType: 'TEAM',
        },
        {
          id: 'obj-team-4',
          title: 'Accelerate enterprise deals',
          progress: 54,
          owner: 'Avery CEO',
          goalType: 'TEAM',
        },
        {
          id: 'obj-emea-1',
          title: 'Stabilize EMEA onboarding',
          progress: 49,
          owner: 'Lea Ops',
          goalType: 'TEAM',
        },
        {
          id: 'obj-apac-1',
          title: 'Win APAC lighthouse accounts',
          progress: 61,
          owner: 'Kenji PM',
          goalType: 'TEAM',
        },
        {
          id: 'obj-support-1',
          title: 'Bring LATAM support to green',
          progress: 44,
          owner: 'Sofia CS',
          goalType: 'TEAM',
        },
      ],
    },
  ],
  recentCheckIns: [
    {
      id: 'ci-1',
      keyResultId: 'kr-team-1',
      keyResultTitle: 'Outbound reply rate 12%+',
      objectiveTitle: 'Increase qualified pipeline 40%',
      ownerName: 'Morgan Lead',
      ownerEmail: 'morgan@okrflow.demo',
      status: 'GREEN',
      value: 72,
      comment: 'Great lift after new sequences',
      weekStart: new Date(),
    },
    {
      id: 'ci-2',
      keyResultId: 'kr-ic-5',
      keyResultTitle: 'Time to aha moment 15 min',
      objectiveTitle: 'Optimize onboarding funnel',
      ownerName: 'Eden IC',
      ownerEmail: 'eden@okrflow.demo',
      status: 'YELLOW',
      value: 45,
      comment: 'Need more guidance for new personas',
      weekStart: new Date(),
    },
    {
      id: 'ci-3',
      keyResultId: 'kr-platform-2',
      keyResultTitle: 'Latency P95 < 300ms',
      objectiveTitle: 'Platform reliability & AI signals',
      ownerName: 'Ravi Data',
      ownerEmail: 'ravi@okrflow.demo',
      status: 'RED',
      value: 35,
      comment: 'Spike after traffic doubled; mitigation in progress.',
      weekStart: new Date(),
    },
    {
      id: 'ci-4',
      keyResultId: 'kr-support-1',
      keyResultTitle: 'Ticket backlog < 80',
      objectiveTitle: 'Bring LATAM support to green',
      ownerName: 'Sofia CS',
      ownerEmail: 'sofia@okrflow.demo',
      status: 'YELLOW',
      value: 42,
      comment: 'Added weekend coverage; backlog trending down.',
      weekStart: new Date(),
    },
    {
      id: 'ci-5',
      keyResultId: 'kr-apac-1',
      keyResultTitle: 'Signed ACV $750k',
      objectiveTitle: 'Win APAC lighthouse accounts',
      ownerName: 'Kenji PM',
      ownerEmail: 'kenji@okrflow.demo',
      status: 'GREEN',
      value: 63,
      comment: 'Tokyo logo signed, Sydney legal in-flight.',
      weekStart: new Date(),
    },
  ],
}

export const demoComments: Comment[] = [
  {
    id: 'c1',
    content: 'Risk flagged: onboarding drop-offs in week 2 cohort.',
    objectiveId: 'obj-team-2',
    keyResultId: 'kr-team-6',
    createdAt: new Date().toISOString(),
    user: demoUsers[0],
  },
  {
    id: 'c2',
    content: 'We need PMM support for APAC launch messaging.',
    objectiveId: 'obj-company-1',
    keyResultId: 'kr-company-1',
    createdAt: new Date().toISOString(),
    user: demoUsers[1],
  },
  {
    id: 'c3',
    content: 'Data latency breaches in EU nightly loads. Paging platform.',
    objectiveId: 'obj-platform-1',
    keyResultId: 'kr-platform-2',
    createdAt: new Date().toISOString(),
    user: demoUsers[5],
  },
  {
    id: 'c4',
    content: 'LATAM backlog dropping 12% week-over-week after shift changes.',
    objectiveId: 'obj-support-1',
    keyResultId: 'kr-support-1',
    createdAt: new Date().toISOString(),
    user: demoUsers[8],
  },
]

export const demoNotifications: AppNotification[] = [
  {
    id: 'n1',
    userId: 'user-admin',
    type: 'checkin',
    message: 'Growth team weekly check-in due tomorrow',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n2',
    userId: 'user-manager',
    type: 'objective',
    message: 'New objective aligned: Optimize onboarding funnel',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n3',
    userId: 'user-employee',
    type: 'comment',
    message: 'Avery commented on Partner pipeline sources 30%',
    read: true,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n4',
    userId: 'user-manager',
    type: 'reminder',
    message: 'Churn reduction KR needs update before Friday',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n5',
    userId: 'user-employee',
    type: 'checkin',
    message: 'ABM warm intro meetings updated to 18/30',
    read: true,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n6',
    userId: 'user-emea',
    type: 'reminder',
    message: 'EMEA activation below target. Review funnel steps.',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n7',
    userId: 'user-apac',
    type: 'objective',
    message: 'Tokyo lighthouse account signed — update ACV in KR.',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n8',
    userId: 'user-data',
    type: 'comment',
    message: 'Data latency spiked in EU. Mitigation runbook triggered.',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n9',
    userId: 'user-latam',
    type: 'checkin',
    message: 'LATAM backlog down 12% WoW after staffing changes.',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
]

export const demoInitiatives = [
  { id: 'init-1', keyResultId: 'kr-company-1', title: 'Close APAC lighthouse logo', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
  { id: 'init-2', keyResultId: 'kr-company-1', title: 'EU channel partner shortlist', status: 'NOT_STARTED', createdAt: start, updatedAt: start },
  { id: 'init-3', keyResultId: 'kr-team-4', title: 'Guided onboarding revamp', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
  { id: 'init-4', keyResultId: 'kr-platform-2', title: 'Cache warmers for EU region', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
  { id: 'init-5', keyResultId: 'kr-support-1', title: 'Weekend triage squad', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
]

export const demoNotificationSettings = {
  emailCheckInReminders: true,
  emailWeeklyDigest: true,
  emailObjectiveUpdates: true,
  pushCheckInReminders: true,
  pushObjectiveComments: true,
  pushDeadlineAlerts: true,
}





