import type { Objective } from '@/hooks/useObjectives'
import type { CheckInSummary } from '@/lib/checkin-summary'
import type { Comment } from '@/hooks/useComments'
import type { AppNotification } from '@/hooks/useNotifications'

export const demoUsers = [
  { id: 'user-admin', name: 'Avery CEO', email: 'avery@okrflow.demo', role: 'ADMIN' },
  { id: 'user-manager', name: 'Morgan Lead', email: 'morgan@okrflow.demo', role: 'MANAGER' },
  { id: 'user-employee', name: 'Eden IC', email: 'eden@okrflow.demo', role: 'EMPLOYEE' },
] as const

export const demoTeams = [
  {
    id: 'team-gtm',
    name: 'Growth',
    members: [demoUsers[1], demoUsers[2]],
  },
  {
    id: 'team-product',
    name: 'Product',
    members: [demoUsers[0], demoUsers[2]],
  },
  {
    id: 'team-cs',
    name: 'Customer Success',
    members: [demoUsers[1]],
  },
  {
    id: 'team-sales',
    name: 'Sales',
    members: [demoUsers[0], demoUsers[1]],
  },
]

const today = new Date()
const start = new Date(today.getFullYear(), 9, 1).toISOString()
const end = new Date(today.getFullYear(), 11, 31).toISOString()

export const demoObjectives: Objective[] = [
  {
    id: 'obj-company-1',
    title: 'Expand into 2 new markets',
    description: 'Land lighthouse customers in APAC and EU',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'COMPANY',
    progressType: 'AUTOMATIC',
    progress: 63,
    score: 0.7,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: null,
    parent: null,
    children: [
      { id: 'obj-team-1', title: 'Increase qualified pipeline 40%' },
      { id: 'obj-team-2', title: 'Improve product onboarding' },
    ],
    keyResults: [
      { id: 'kr-company-1', title: 'Signed ARR from new regions', weight: 40, target: 1000000, current: 620000, unit: 'USD', progress: 62, initiativeCount: 3 },
      { id: 'kr-company-2', title: 'Regional NPS > 70', weight: 30, target: 70, current: 52, progress: 74, initiativeCount: 2 },
      { id: 'kr-company-3', title: 'Partner pipeline sources 30%', weight: 30, target: 30, current: 18, progress: 60, initiativeCount: 1 },
    ],
    _count: { children: 2 },
  },
  {
    id: 'obj-team-1',
    title: 'Increase qualified pipeline 40%',
    description: 'Focus on PLG and outbound efficiency',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 72,
    score: 0.78,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[1],
    team: demoTeams[0],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [{ id: 'obj-ic-1', title: 'Launch ABM motion' }],
    keyResults: [
      { id: 'kr-team-1', title: 'Outbound reply rate 12%+', weight: 30, target: 12, current: 10.5, unit: '%', progress: 88, initiativeCount: 4 },
      { id: 'kr-team-2', title: 'SQL to Opp conversion 35%', weight: 30, target: 35, current: 28, unit: '%', progress: 80, initiativeCount: 2 },
      { id: 'kr-team-3', title: 'Pipeline coverage 4.5x', weight: 40, target: 4.5, current: 3.2, progress: 71, initiativeCount: 3 },
    ],
    _count: { children: 1 },
  },
  {
    id: 'obj-team-2',
    title: 'Improve product onboarding',
    description: 'Reduce time-to-value and activation drop-offs',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 58,
    score: 0.64,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: demoTeams[1],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [{ id: 'obj-ic-2', title: 'Optimize onboarding funnel' }],
    keyResults: [
      { id: 'kr-team-4', title: 'Activation rate 65%', weight: 40, target: 65, current: 52, unit: '%', progress: 80, initiativeCount: 2 },
      { id: 'kr-team-5', title: 'Time to first value < 1 day', weight: 30, target: 1, current: 1.4, unit: 'days', progress: 60, initiativeCount: 2 },
      { id: 'kr-team-6', title: 'Onboarding drop-off < 25%', weight: 30, target: 25, current: 33, unit: '%', progress: 64, initiativeCount: 1 },
    ],
    _count: { children: 1 },
  },
  {
    id: 'obj-team-3',
    title: 'Reduce churn to <4%',
    description: 'Improve adoption and renewals in top 50 accounts',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 66,
    score: 0.74,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[1],
    team: demoTeams[2],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-team-7', title: 'NPS > 55', weight: 40, target: 55, current: 49, unit: 'score', progress: 89, initiativeCount: 2 },
      { id: 'kr-team-8', title: 'Gross churn <4%', weight: 30, target: 4, current: 5.4, unit: '%', progress: 73, initiativeCount: 2 },
      { id: 'kr-team-9', title: 'Adoption in top 50 accounts 70%', weight: 30, target: 70, current: 54, unit: '%', progress: 77, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-team-4',
    title: 'Accelerate enterprise deals',
    description: 'Land 3 enterprise wins and expand ACV',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'TEAM',
    progressType: 'AUTOMATIC',
    progress: 54,
    score: 0.6,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[0],
    team: demoTeams[3],
    parent: { id: 'obj-company-1', title: 'Expand into 2 new markets' },
    children: [],
    keyResults: [
      { id: 'kr-team-10', title: 'Enterprise ACV $1.5M', weight: 40, target: 1500000, current: 820000, unit: 'USD', progress: 55, initiativeCount: 3 },
      { id: 'kr-team-11', title: 'Win rate 28%', weight: 30, target: 28, current: 21, unit: '%', progress: 75, initiativeCount: 2 },
      { id: 'kr-team-12', title: 'Discovery-to-demo < 5 days', weight: 30, target: 5, current: 7, unit: 'days', progress: 60, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-ic-1',
    title: 'Launch ABM motion',
    description: 'Pilot ABM for top 50 accounts',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'INDIVIDUAL',
    progressType: 'AUTOMATIC',
    progress: 76,
    score: 0.82,
    status: 'IN_PROGRESS',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[2],
    team: demoTeams[0],
    parent: { id: 'obj-team-1', title: 'Increase qualified pipeline 40%' },
    children: [],
    keyResults: [
      { id: 'kr-ic-1', title: 'Target list coverage 95%', weight: 40, target: 95, current: 92, unit: '%', progress: 97, initiativeCount: 2 },
      { id: 'kr-ic-2', title: 'Warm intro meetings 30', weight: 30, target: 30, current: 18, progress: 60, initiativeCount: 2 },
      { id: 'kr-ic-3', title: 'ABM influenced pipeline $250k', weight: 30, target: 250000, current: 140000, progress: 56, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
  {
    id: 'obj-ic-2',
    title: 'Optimize onboarding funnel',
    description: 'Increase guided onboarding completion',
    cycle: 'Q4-2024',
    startAt: start,
    endAt: end,
    goalType: 'INDIVIDUAL',
    progressType: 'AUTOMATIC',
    progress: 48,
    score: 0.52,
    status: 'AT_RISK',
    fiscalQuarter: 4,
    createdAt: start,
    owner: demoUsers[2],
    team: demoTeams[1],
    parent: { id: 'obj-team-2', title: 'Improve product onboarding' },
    children: [],
    keyResults: [
      { id: 'kr-ic-4', title: 'Guided onboarding completion 75%', weight: 50, target: 75, current: 48, unit: '%', progress: 64, initiativeCount: 2 },
      { id: 'kr-ic-5', title: 'Time to aha moment 15 min', weight: 25, target: 15, current: 22, unit: 'minutes', progress: 68, initiativeCount: 1 },
      { id: 'kr-ic-6', title: 'Onboarding CSAT 4.5', weight: 25, target: 4.5, current: 4.0, progress: 89, initiativeCount: 1 },
    ],
    _count: { children: 0 },
  },
]

export const demoCheckInSummary: CheckInSummary = {
  hero: {
    avgProgress: 64,
    completionRate: 42,
    atRiskObjectives: 2,
    objectiveCount: 5,
    scoreAverage: 0.71,
  },
  weeklySummary: {
    onTrack: 4,
    atRisk: 2,
    offTrack: 1,
    dueThisWeek: 3,
  },
  teamHeatmap: [
    { teamId: 'team-gtm', teamName: 'Growth', progress: 72, status: 'green', objectiveCount: 2, memberCount: 6 },
    { teamId: 'team-product', teamName: 'Product', progress: 58, status: 'yellow', objectiveCount: 2, memberCount: 5 },
    { teamId: 'team-cs', teamName: 'Customer Success', progress: 66, status: 'green', objectiveCount: 1, memberCount: 3 },
    { teamId: 'team-sales', teamName: 'Sales', progress: 54, status: 'yellow', objectiveCount: 1, memberCount: 4 },
  ],
  heatmap: [
    {
      keyResultId: 'kr-team-1',
      keyResultTitle: 'Outbound reply rate 12%+',
      objectiveTitle: 'Increase qualified pipeline 40%',
      ownerName: 'Morgan Lead',
      weeklyProgress: [
        { value: 72, status: 'green', date: new Date() },
        { value: 68, status: 'yellow', date: new Date() },
      ],
    },
    {
      keyResultId: 'kr-team-5',
      keyResultTitle: 'Time to first value < 1 day',
      objectiveTitle: 'Improve product onboarding',
      ownerName: 'Avery CEO',
      weeklyProgress: [
        { value: 52, status: 'yellow', date: new Date() },
        { value: 60, status: 'green', date: new Date() },
      ],
    },
  ],
  alignment: [
    {
      id: 'obj-company-1',
      title: 'Expand into 2 new markets',
      progress: 63,
      owner: 'Avery CEO',
      goalType: 'COMPANY',
      children: [
        {
          id: 'obj-team-1',
          title: 'Increase qualified pipeline 40%',
          progress: 72,
          owner: 'Morgan Lead',
          goalType: 'TEAM',
          children: [
            {
              id: 'obj-ic-1',
              title: 'Launch ABM motion',
              progress: 76,
              owner: 'Eden IC',
              goalType: 'INDIVIDUAL',
            },
          ],
        },
        {
          id: 'obj-team-2',
          title: 'Improve product onboarding',
          progress: 58,
          owner: 'Avery CEO',
          goalType: 'TEAM',
          children: [
            {
              id: 'obj-ic-2',
              title: 'Optimize onboarding funnel',
              progress: 48,
              owner: 'Eden IC',
              goalType: 'INDIVIDUAL',
            },
          ],
        },
        {
          id: 'obj-team-3',
          title: 'Reduce churn to <4%',
          progress: 66,
          owner: 'Morgan Lead',
          goalType: 'TEAM',
        },
        {
          id: 'obj-team-4',
          title: 'Accelerate enterprise deals',
          progress: 54,
          owner: 'Avery CEO',
          goalType: 'TEAM',
        },
      ],
    },
  ],
  recentCheckIns: [
    {
      id: 'ci-1',
      keyResultId: 'kr-team-1',
      keyResultTitle: 'Outbound reply rate 12%+',
      objectiveTitle: 'Increase qualified pipeline 40%',
      ownerName: 'Morgan Lead',
      ownerEmail: 'morgan@okrflow.demo',
      status: 'GREEN',
      value: 72,
      comment: 'Great lift after new sequences',
      weekStart: new Date(),
    },
    {
      id: 'ci-2',
      keyResultId: 'kr-ic-5',
      keyResultTitle: 'Time to aha moment 15 min',
      objectiveTitle: 'Optimize onboarding funnel',
      ownerName: 'Eden IC',
      ownerEmail: 'eden@okrflow.demo',
      status: 'YELLOW',
      value: 45,
      comment: 'Need more guidance for new personas',
      weekStart: new Date(),
    },
  ],
}

export const demoComments: Comment[] = [
  {
    id: 'c1',
    content: 'Risk flagged: onboarding drop-offs in week 2 cohort.',
    objectiveId: 'obj-team-2',
    keyResultId: 'kr-team-6',
    createdAt: new Date().toISOString(),
    user: demoUsers[0],
  },
  {
    id: 'c2',
    content: 'We need PMM support for APAC launch messaging.',
    objectiveId: 'obj-company-1',
    keyResultId: 'kr-company-1',
    createdAt: new Date().toISOString(),
    user: demoUsers[1],
  },
]

export const demoNotifications: AppNotification[] = [
  {
    id: 'n1',
    userId: 'user-admin',
    type: 'checkin',
    message: 'Growth team weekly check-in due tomorrow',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n2',
    userId: 'user-manager',
    type: 'objective',
    message: 'New objective aligned: Optimize onboarding funnel',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n3',
    userId: 'user-employee',
    type: 'comment',
    message: 'Avery commented on Partner pipeline sources 30%',
    read: true,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n4',
    userId: 'user-manager',
    type: 'reminder',
    message: 'Churn reduction KR needs update before Friday',
    read: false,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n5',
    userId: 'user-employee',
    type: 'checkin',
    message: 'ABM warm intro meetings updated to 18/30',
    read: true,
    metadata: null,
    createdAt: new Date().toISOString(),
  },
]

export const demoInitiatives = [
  { id: 'init-1', keyResultId: 'kr-company-1', title: 'Close APAC lighthouse logo', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
  { id: 'init-2', keyResultId: 'kr-company-1', title: 'EU channel partner shortlist', status: 'NOT_STARTED', createdAt: start, updatedAt: start },
  { id: 'init-3', keyResultId: 'kr-team-4', title: 'Guided onboarding revamp', status: 'IN_PROGRESS', createdAt: start, updatedAt: start },
]

export const demoNotificationSettings = {
  emailCheckInReminders: true,
  emailWeeklyDigest: true,
  emailObjectiveUpdates: true,
  pushCheckInReminders: true,
  pushObjectiveComments: true,
  pushDeadlineAlerts: true,
}
